"""adiciona coluna valor_rebobinamento

Revision ID: 4081327c8e09
Revises: 5b7e4f56c041
Create Date: 2026-07-07 09:09:50.198165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4081327c8e09'
down_revision: Union[str, Sequence[str], None] = '5b7e4f56c041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
