"""Criacao inicial do banco de dados

Revision ID: 5b7e4f56c041
Revises: 
Create Date: 2026-07-06 14:00:38.663229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5b7e4f56c041'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemorcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cv', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rpm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tensao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fases', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('polos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('problema_relatado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caminho_foto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('motor_descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cliente_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('valor_rebobinamento', sa.Float(), nullable=False),
    sa.Column('descricao_mao_de_obra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_mao_de_obra', sa.Float(), nullable=False),
    sa.Column('valor_pecas', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precopeca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precoservico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fases', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('polos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preco_rebobinagem', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precoservico')
    op.drop_table('precopeca')
    op.drop_table('orcamento')
    op.drop_table('motor')
    op.drop_table('itemorcamento')
    op.drop_table('cliente')
    # ### end Alembic commands ###
